<%@ Page Language="C#" MasterPageFile="~/registration.master" AutoEventWireup="true" CodeFile="searchlicence.aspx.cs" Inherits="searchlicence" %>

<asp:Content ID="Content1" runat="server" 
    contentplaceholderid="ContentPlaceHolder1">
    <a href="mainpage.aspx">
    <p style="background-color: #000000; color: #FFFFFF; font-family: cursive; font-size: large; font-weight: bold; text-transform: capitalize; text-align: center;">
        AUTOMATION OF VEHICLE REGISTRATION SYSTEM</p>
    </a>
    <table class="style1">
        <tr>
            <td class="style4">
            </td>
            <td class="style7">
            </td>
            <td class="style2">
            </td>
        </tr>
        <tr>
            <td class="style5">
                <asp:RadioButtonList ID="RadioButtonList1" runat="server" AutoPostBack="True" 
                    Font-Bold="True" Font-Names="cambiri" Font-Size="Medium" Font-Underline="True" 
                    ForeColor="White" Height="138px" style="margin-top: 0px" Width="252px">
                    <asp:ListItem>Search By Licence No.</asp:ListItem>
                    <asp:ListItem>Search By Licence Holder Name</asp:ListItem>
                </asp:RadioButtonList>
            </td>
            <td class="style8">
                <br />
                <br />
                <asp:TextBox ID="sbln" runat="server" 
                    style="position: relative; top: 23px; left: 1px; height: 22px; margin-top: 0px" 
                    Width="196px" BackColor="#999999" BorderColor="#333333" 
                    BorderStyle="Groove"></asp:TextBox>
                <br />
                <br />
                <br />
                <br />
&nbsp;
                <asp:TextBox ID="sblh" runat="server" 
                    style="position: relative; top: 1px; left: -6px; height: 22px; width: 196px" BackColor="#999999" BorderColor="#333333" 
                    BorderStyle="Groove"></asp:TextBox>
&nbsp;&nbsp;&nbsp;
                <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <br />
                <br />
            </td>
            <td class="style3">
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <asp:Button ID="search" runat="server" BackColor="Black" BorderColor="White" 
                    BorderStyle="Groove" BorderWidth="1px" Font-Names="cursive" Font-Size="Medium" 
                    Font-Underline="True" ForeColor="White" onclick="search_Click" Text="Search" 
                    Width="72px" />
            </td>
        </tr>
        <tr>
            <td class="style6">
                <asp:Label ID="Label1" runat="server" ForeColor="Maroon" 
                    Text="Incorrect Name Or Licence No." Visible="False"></asp:Label>
            </td>
            <td class="style9">
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
    </table>
   
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" 
                        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" 
                        BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" 
                        Font-Names="Cambria" Font-Size="Medium" 
                        HorizontalAlign="Center" PageIndex="1" SelectedIndex="0" ShowFooter="True" 
                        style="position: relative; top: 50px; left: 8px" EditIndex="1" 
                        EnableSortingAndPagingCallbacks="True">
        <EmptyDataTemplate>
            RECORD NOT FOUND
        </EmptyDataTemplate>
        <FooterStyle BackColor="White" ForeColor="#000066" Height="20px" />
        <HeaderStyle BackColor="#006699" BorderColor="White" BorderStyle="Groove" 
            BorderWidth="2px" Font-Bold="True" Font-Names="Cambria" 
            Height="80px" Width="200px" ForeColor="White" />
        <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
        <RowStyle ForeColor="#000066" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#007DBB" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#00547E" />
    </asp:GridView>
    
</asp:Content>
<asp:Content ID="Content2" runat="server" contentplaceholderid="head">
    <style type="text/css">
        .style1
        {
            width: 50%;
            position: relative;
            top: 12px;
            left: 300px;
            height: 182px;
        }
        .style2
        {
            height: 20px;
        }
        .style3
        {
            height: 82px;
        }
        .style4
        {
            height: 20px;
            width: 259px;
        }
        .style5
        {
            height: 82px;
            width: 259px;
        }
        .style6
        {
            width: 259px;
        }
        .style7
        {
            height: 20px;
            width: 211px;
        }
        .style8
        {
            height: 82px;
            width: 211px;
        }
        .style9
        {
            width: 211px;
        }
    </style>
</asp:Content>


